### ISSUE TITLE
모바일 사용관련

### ISSUE THREAD

**Issue by Clickin** [Stdev17/arenatime#1]
몇 번 써봤는데 돈내고 aws 람다까지 굴려주시는거 감사하고 지금 기능으로도 충분히 잘 쓰고 있습니다.
근데 바쁘셔서 모바일 대응이 안된건진 몰라도 대충 훑어보니까 절대좌표로 잡아놓으셔서 그런가 모바일에서는 짤려서 캐릭터 선택을 할 수가 없네요.
다들 앱플레이어로 게임하는게 아니라서 모바일에서 사용하기 힘들면 데이터가 덜 수집되지 않을까 싶습니다. 
그리고 이미지는 왜 업로드 받으시는 건가요? 이미지인식>자동입력 같은 계획이 있으신건지 궁금합니다.

**Comment by Stdev17** [comment]
으아아악 Issues 1 지금 봤다 죄송합니다 ㅠㅠ
이 글 보는 시점에선 모바일 페이지로 렌더링되게 해서 관련 이슈는 없는 것 같아요
이미지는 굳이 업로드할 필요 없고.. 업로드한다면 이용자들이 원본을 확인할 수 있게 하려구요
OpenCV로 인식해서 자동 입력해주는 걸 람다에 어찌 굴러가게 배포해서 운영해볼까 생각은 했는데.. 실력이 미천해서 지지부진합니다..
